language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jakecallery/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jakecallery/docker-react npm run test
  